name: Send mail to teacher


on:
  [push]
jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
     - name: Send mail
       uses: dawidd6/action-send-mail@v3
       with:
    # Required mail server address:
         server_address: smtp.gmail.com
    # Required mail server port:
         server_port: 465
    # Optional (recommended): mail server username:
         # username: ${{secrets.MAIL_USERNAME}}
    # Optional (recommended) mail server password:
         # password: ${{secrets.MAIL_PASSWORD}}
    # Required mail subject:
         subject: Github Actions job result
    # Required recipients' addresses:
         to: galina.rudolf@informatik.tu-freiberg.de
    # Required sender full name (address can be skipped):
         from: Luke Skywalker # <user@example.com>
    # Optional whether this connection use TLS (default is true if server_port is 465)
         secure: true
    # Optional plain body:
         body: Build job of ${{github.repository}} completed successfully!
